### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hemdan-dev** [bakoushin/medooze-player#8]
Hello @bakoushin 

Can you let me know if player still doesn't work?

Thank you

**Comment by bakoushin** [comment]
@hemdan-dev could you please elaborate?

**Comment by hemdan-dev** [comment]
Am just followed your issue on medooze package about medooze player with record, but didn't find answer
and tried to install this repo with latest version of medooze (0.127.1)
also tried medooze playback example but the same result
i got same error you got, and want to know if this issue is fixed or you got another way to do

![image](https://user-images.githubusercontent.com/52411897/204022431-7e96dfa4-0733-4682-b1ee-d2abeb1bc526.png)

**Comment by bakoushin** [comment]
You may consider recoding using FFmpeg or GStreamer: https://github.com/bakoushin/medooze-streamer-demo
